stages:
  raw_dataset_creation:
    cmd: python src/data/loading_data.py --config=params.yaml
    deps:
    - src/data/loading_data.py
    - data/external/kc_house_data.csv
    outs:
    - data/raw/raw_data.csv
  
  transform data:
    cmd: python src/data/transform_data.py --config=params.yaml
    deps:
    - src/data/transform_data.py
    - data/raw/raw_data.csv
    outs:
    - data/interim/transformed_data.csv
  
  split_data:
    cmd: python src/data/split_data.py --config=params.yaml
    deps:
    - src/data/split_data.py
    - data/interim/transformed_data.csv
    outs:
    - data/processed/train.csv
    - data/processed/test.csv

  model_train:
    cmd: python src/models/training_pipeline.py --config=params.yaml
    deps:
    - data/processed/train.csv
    - data/processed/test.csv
    - src/models/training_pipeline.py
    params:
    - model_config.params.max_depth
    - model_config.params.n_estimators

  log_production_model:
    cmd: python src/models/production_model_selection.py --config=params.yaml
    deps:
    - src/models/production_model_selection.py
    params:
    - model_config.params.max_depth
    - model_config.params.n_estimators
    outs:
    - models/model.joblib
