external_data_config:
  external_data_csv: data/external/kc_house_data.csv

raw_data_config: 
  raw_data_csv: data/raw/raw_data.csv
  model_var: ['date','price','bedrooms','sqft_living','sqft_lot','floors','waterfront', 'view', 'condition', 'grade', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long', 'sqft_living15', 'sqft_lot15']
  train_test_split_ratio: 0.2
  target: price 
  random_state: 42
  transformed_data_csv: data/interim/transformed_data.csv

processed_data_config:
  train_data_csv: data/processed/train.csv
  test_data_csv:  data/processed/test.csv

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: model_iteration1
  run_name: regression_model_run
  registered_model_name: regression_model
  remote_server_uri: http://127.0.0.1:8080
 
preprocess_config:
  imputer:
  scaler:
    name: StandardScaler
    feats:
  encoder:
  pca:

model_config: 
  model_name: RandomForestRegressor
  params:
    n_estimators: 100
    max_depth: 6

model_dir: models/model.joblib

model_webapp_dir: webapp/model_webapp_dir/model.joblib

model_monitor:
  target_col_name: target
  monitor_dashboard_html: reports/data_and_target_drift_dashboard.html
